"""
Prior Graph Builder: load pre-built prior graph as dense adjacency matrix.

Load pre-built prior graph (prior_graph.pt) and convert to dense adjacency matrix 
for DAGMA causal graph learning.

prior_graph.pt is generated by data/prior_graph/build_prior_graph.py, 
containing edge_index [2, n_edges], gene_list, etc.
"""

from pathlib import Path

import numpy as np
import torch


def load_prior_graph(
    graph_path: Path,
    gene_names: list[str],
) -> tuple[np.ndarray, list[str]]:
    """Load prior graph and convert to dense adjacency matrix
    
    Args:
        graph_path: prior_graph.pt file path
        gene_names: expected gene list. If provided, verify consistency with 
                    the gene list in the prior graph and reorder accordingly. 
                    If not provided, use the gene_list from the prior graph.
    
    Returns:
        prior_adj: dense adjacency matrix [n_genes, n_genes], numpy float32
        gene_list: gene name list, corresponding to matrix row and column order
    """
    data = torch.load(graph_path, map_location='cpu', weights_only=False)
    
    graph_genes = data['gene_list']  # sorted symbol list
    edge_index = data['edge_index']  # [2, n_edges]
    n_genes = data['n_genes']
    
    if gene_names is not None:
        # verify gene set consistency
        set_graph = set(graph_genes)
        set_expected = set(gene_names)
        if set_graph != set_expected:
            missing = set_expected - set_graph
            extra = set_graph - set_expected
            raise ValueError(
                f"Prior graph gene list is inconsistent with the dataset:\n"
                f"  Dataset has but prior graph lacks: {len(missing)} genes\n"
                f"  Prior graph has but dataset lacks: {len(extra)} genes"
            )
        
        # Remap edge_index if gene order differs
        if gene_names != graph_genes:
            old_to_new = {old_i: gene_names.index(g) 
                          for old_i, g in enumerate(graph_genes)}
            new_src = torch.tensor([old_to_new[i.item()] for i in edge_index[0]])
            new_tgt = torch.tensor([old_to_new[i.item()] for i in edge_index[1]])
            edge_index = torch.stack([new_src, new_tgt])
            graph_genes = gene_names
    
    # Convert edge_index to dense adjacency
    adj = np.zeros((n_genes, n_genes), dtype=np.float32)
    if edge_index.numel() > 0:
        src = edge_index[0].long().numpy()
        tgt = edge_index[1].long().numpy()
        adj[src, tgt] = 1.0
    
    return adj, graph_genes
